name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: corepack enable

      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable

      - name: npm install
        run: npm ci

      - name: Run Test
        run: npm run test
